[package]
name = "dsp_seed_finder"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
incremental = true
debug = true

[dependencies]
crossbeam-channel = "0.5.15"
once_cell = "1.19.0"
serde = { version = "1.0.193", features = ["derive", "rc"] }
postgres =  { version = "0.19.13" }
