CREATE UNLOGGED TABLE stars (
    id INT PRIMARY KEY,
    seed INT,
    dyson_radius INT,

    ore_iron INT,
    ore_copper INT,
    ore_silicium INT,
    ore_titanium INT,
    ore_stone INT,
    ore_coal INT,
    ore_oil INT,
    ore_fireice INT,
    ore_diamond INT,
    ore_fractal INT,
    ore_crysrub INT,
    ore_grat INT,
    ore_bamboo INT,
    ore_mag INT,

    start_dist REAL,
    luminosity REAL,
    star_index SMALLINT,
    type SMALLINT,
    spectr SMALLINT
);
CREATE UNLOGGED TABLE planets (
    star_id INT,

    estimate_iron INT,
    estimate_copper INT,
    estimate_silicium INT,
    estimate_titanium INT,
    estimate_stone INT,
    estimate_coal INT,
    estimate_oil INT,
    estimate_fireice INT,
    estimate_diamond INT,
    estimate_fractal INT,
    estimate_crysrub INT,
    estimate_grat INT,
    estimate_bamboo INT,
    estimate_mag INT,
    min_iron INT,
    min_copper INT,
    min_silicium INT,
    min_titanium INT,
    min_stone INT,
    min_coal INT,
    min_oil INT,
    min_fireice INT,
    min_diamond INT,
    min_fractal INT,
    min_crysrub INT,
    min_grat INT,
    min_bamboo INT,
    min_mag INT,
    max_iron INT,
    max_copper INT,
    max_silicium INT,
    max_titanium INT,
    max_stone INT,
    max_coal INT,
    max_oil INT,
    max_fireice INT,
    max_diamond INT,
    max_fractal INT,
    max_crysrub INT,
    max_grat INT,
    max_bamboo INT,
    max_mag INT,

    sun_distance REAL,
    temperature REAL,
    gas_h REAL,
    gas_d REAL,
    gas_i REAL,
    index SMALLINT,
    orbiting SMALLINT,
    water_item SMALLINT,
    satellites SMALLINT,
    theme_id SMALLINT,
    gas_giant BOOL,
    inside_ds BOOL,
    tidal_lock BOOL,
    UNIQUE(star_id, index)
);

-- Create user for RESTful API
CREATE USER api_user WITH PASSWORD 'api_password';

GRANT USAGE ON SCHEMA public TO api_user;
GRANT SELECT ON stars TO api_user;
GRANT SELECT ON planets TO api_user;