services:
  seedfinder:
    image: toti330/dsp_seed_finder:0.7.0@sha256:58d968aa4a6661b7b203a6716bd0de7c5a39763d688410b1d600d617513181ca
    container_name: seedfinder
    environment:
      START_SEED: ${START_SEED:-0}
      END_SEED: ${END_SEED:-1000}
      NO_TUI: 1
      PG_USER: postgres
      PG_PASS: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD}
      PG_PORT: 5432
      PG_DBNAME: dsp
      PG_NETLOC: 127.0.0.1
      LOG_LEVEL: ${LOG_LEVEL:-info}
    network_mode: host
    restart: "no"
