services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: dsp
    volumes:
      - "../data:/var/lib/postgresql/data"
      - "./init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  seedfinder:
    image: toti330/seedfinder:0.2.0
    container_name: seedfinder
    environment:
      END_SEED: 100000 # max is 10,000,000 (10m)
      NO_TUI: 1 # Disable progress tui
      PG_USER: postgres
      PG_PASS: rootpassword # Default values
      PG_PORT: 5432
      PG_DBNAME: dsp
      PG_NETLOC: host.docker.internal
    restart: on-failure
    depends_on:
      - postgres
  api:
    image: superb3333/postgres_api
    container_name: api
    environment:
      PG_DBNAME: dsp
      PG_USER: api_user
      PG_PASS: api_password