[package]
name = "dsp_seed_finder"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
incremental = true
debug = true

[[bin]]
name = "dsp_seed_finder"
path = "src/main.rs"
required-features = ["binary"]

[lib]
required-features = ["python"]
name = "dsp_generator"
path = "src/python.rs"
module-name = "dsp_generator"
crate-type = ["cdylib"]


# Dependencies for all builds
[dependencies]
once_cell = "1.19.0"
serde = { version = "1.0.193", features = ["derive", "rc"] }

# Dependencies for binary
crossbeam-channel = {  version = "0.5.15", optional = true }
postgres = { version =  "0.19.13", optional = true }
crossterm = { version = "0.29.0", optional = true }
anyhow = { version = "1.0.103", optional = true }
lazy_static = { version = "1.5.0", optional = true }
itertools = { version = "0.15.0", optional = true }


# Dependencies for Python build
pyo3 = { version = "0.29.0", features = ["full"], optional = true}
pythonize = { version = "0.29.0", optional = true }



[features]
default = ["binary"]
binary = ["crossbeam-channel", "postgres", "crossterm", "anyhow", "lazy_static", "itertools"]
python = ["pyo3", "pythonize"]
